-d C:\Users\imaoca09\OneDrive\source\tangnano\instructions\impl\gwsynthesis\instructions.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\imaoca09\OneDrive\source\tangnano\instructions\src\instructions.cst
-cfg C:\Users\imaoca09\OneDrive\source\tangnano\instructions\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
